# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BKVelo
logo: weblogo.png
email: bkvelo.org.uk@gmail.com
# A strapline for your site
description: > # this means to ignore newlines until "baseurl:"
  To Sweet's and Beyond....
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bkvelo.org.uk" # the base hostname & protocol for your site

#Social Media
facebook_username: BrentKnollVelo
github_username:
instagram_username: bkvelo
twitter_username: bkvelo
youtube_username: UCUJSkCSmA6sBUHh8YkZfPSA
strava_clubid: 125486

# Build settings
include: ['_pages']
markdown: kramdown

#Have to show future posts for future events.
future: true
